### ISSUE TITLE
How snATAC jacard works?

### ISSUE THREAD

**Issue by seishin0125** [r3fang/snATAC#10]
I couldn't see the source code of snATAC jacard, therefore I tried snATAC jacard with my test data.
However, I couldn't make out the results.

Input test data is as below (not resized peaks)
>test.bed
chr1	1	1000	test_a
chr1	2001	3000	test_a
chr1	10001	20000	test_a
chr1	30001	40000	test_a
chr1	1	1000	test_b
chr1	10001	20000	test_b
chr1	10001	20000	test_c
chr1	30001	40000	test_c
>test.xgi
test_a
test_b
test_c
>test.ygi
chr1	1	1000
chr1	1001	2000
chr1	2001	3000
chr1	10001	20000
chr1	20001	30000
chr1	30001	40000

>test.mat (this is the output of read.table(as.matrix("test.mat")) in R)
  V1 V2 V3 V4 V5 V6
1  1  0  1  1  0  1
2  1  0  0  1  0  0
3  0  0  0  1  0  1

And the output of "snATAC jacard -i test.mat -x 3 -y 6 -o test.jaccard" was below
0.00	600.00	600.00	
600.00	0.00	500.00	
600.00	500.00	0.00	

This result seems that the function "snATAC jaccard" calculate the Jaccard distance of the vector assigned to each cell (e.g. (1,0,1,1,0,1) for test_a cell) and we have to resize the width of each peak in .ygi.
However, if so, the Jaccard distance between test_a and test_b would be 0.5(2/4) and the value of 1000x jaccard would be 500. Why is the result is slightly different from the expected result?

(I think "1" is added both denominator and numerator. (2/4→3/5→0.6, 1/3→2/4→0.5) )

**Comment by r3fang** [comment]
Hi, I did not notice that there was an issue. Please note that snATAC is no longer under maintenance, please go to our new package SnapATAC (https://github.com/r3fang/SnapATAC)
