### ISSUE TITLE
BWA mapping

### ISSUE THREAD

**Issue by shengyongniu** [r3fang/snATAC#2]
Hi there,

Really appreciate for your pipeline of snATAC-seq. 
I follow your tutorial and execute the commands; however, some of the execution are quite slow (takes more than one day). 
Could you please provide the output file in the step of 
```
          bwa mem -t 1 mm10.fa \
          p56.rep1.R1.decomplex.fastq.gz \
          p56.rep1.R2.decomplex.fastq.gz \
          | samtools view -bS - > p56.rep1.bam
```
Also, is it possible to run this command in multiple cores?

Sincerely,
Simon

**Comment by r3fang** [comment]
Yes, you can use different threads by changing -t .

**Comment by shengyongniu** [comment]
Is it possible to use multiple CPU cores?
2018/1/11 上午1:11於 "Rongxin Fang" <notifications@github.com>寫道：

**Comment by r3fang** [comment]
Yes, you can use any number of cores as you like according to your computational resources.

**Comment by r3fang** [comment]
I also added the output file p56.rep1.bam in the same folder so you can download.

**Comment by shengyongniu** [comment]
Really appreciate for your help!
2018/1/11 上午11:08於 "Rongxin Fang" <notifications@github.com>寫道：
