### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by shengyongniu** [r3fang/snATAC#4]
Hi there,

I got the number 4598 from the command  `wc -l p56.rep1.xgi` and 
184519 from `wc -l p56.rep1.ygi`. 
After I use the command `./bin/snATAC_jacard -i p56.rep1.mat -x 4598  -y 184519 -o p56.rep1.jacard`
it shows: **Segmentation fault**

Do you have any suggestion?

Simon

**Comment by r3fang** [comment]
./bin/snATAC jacard usually requires large memory, did you run it on your PC, can you try it on a server with larger memory?

**Comment by r3fang** [comment]
Let me know if you have / have't solved the problem

**Comment by shengyongniu** [comment]
I run it on a server with 512G memory before, but it still doesn't work. How much RAM do you suggest? Thanks!

Simon

**Comment by r3fang** [comment]
Then it should not be memory issue!
two possibilities:
case1:
you run it in a wrong way
if you run by this command
./bin/snATAC_jacard then you should run it in the following way:
./bin/snATAC_jacard p56.rep1.mat 4598 184519 p56.rep1.jacard

if you run by this command
./bin/snATAC jacard then you should run it in the following way:
./bin/snATAC_jacard -i p56.rep1.mat -x 4598 -y 184519 -o p56.rep1.jacard

case2 - compile issue
type in ./bin/snATAC_jacard 
if you see help message it is fine
Usage: ./bin/snATAC_jacard  <in.mat> <num_row> <num_col> <out.txt>

if you don't see help message then re-compile it:
gcc -g -O2 src/calculate_jacard_index_matrix.c -o bin/snATAC_jacard

Good luck!

**Comment by r3fang** [comment]
Let me know if it solves your problem

**Comment by shengyongniu** [comment]
It works. Thanks a lot!
