### ISSUE TITLE
Permission Denied to Download Files from http://renlab.sdsc.edu/r3fang/snATAC/

### ISSUE THREAD

**Issue by julalipa** [r3fang/snATAC#5]
Hi, First - I wanted to say thanks and well done on establishing this protocol. This is very impressive and interesting! We are very interested in scATAC-seq of tissue samples and would like to look at your dataset. However, it seems that not all the files in the http://renlab.sdsc.edu/r3fang/snATAC/ folder are open for public download. For about half of them (e11.5_R2, e12.5_R2, e14.5_R2, e15.5_R2, e16.5_R2, p0_R2, p56_R1, p56_R2), the following error arises when trying to Download

```
-sh-4.1$ wget http://renlab.sdsc.edu/r3fang/snATAC/p56_R1.decomplex.fastq.gz
--2018-03-07 11:23:55--  http://renlab.sdsc.edu/r3fang/snATAC/p56_R1.decomplex.fastq.gz
Resolving renlab.sdsc.edu... 198.202.90.216
Connecting to renlab.sdsc.edu|198.202.90.216|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-07 11:23:55 ERROR 403: Forbidden.
```

We wanted to look at the full dataset, would you be able to provide download access for all the decomplexed fastq files? 

Many thanks, Julia

**Comment by r3fang** [comment]
i have changed the permission, you should be able to download, let me know if not.

**Comment by julalipa** [comment]
Thanks a lot, I was able to download everything now! Cheers!

**Comment by r3fang** [comment]
Hey Julia, FYI, i just split all fastqs into two replicates :) you can check it out by this link http://renlab.sdsc.edu/r3fang/snATAC/
