### ISSUE TITLE
Unable to reproduce... 

### ISSUE THREAD

**Issue by jeewonyang** [r3fang/snATAC#6]
Hi, I am interested in the snATAC method, and I was trying to first reproduce your pipeline to make sure that I can do the same with my dataset. 

I copied the tutorial exactly (except for downloading the mm10.fa, since I already have local BWA Index for mm10), and made sure that I am doing the same thing. However, when I filter out the barcodes with your pipeline (>1000 reads per cell, 3% consecutive promoter coverage, 20% reads in peak), I'm not getting 1464 barcodes--instead, 4600 of them--, and I am unable to produce any good clustering on the tSNE as it shows in the pipeline. I read in the paper that you got better clustering using the distal promoter regions, so I also tried creating a bed file containing regions +2kb upstream of the refSeq promoter.bed file as well, yet I still don't see much of a difference.

Would you be able to help me understand how you filtered out the barcode...? (+ tips on making good tSNE maps?)

**Comment by r3fang** [comment]
1) That must be a mistake for the parameters (>1000 reads per cell, 3% consecutive promoter coverage, 20% reads in peak) this will give more cells, i will update the parameter shortly. 3% consecutive promoter is lower than what we have used before. 
2) the reason that you did not see a good seperation of clusters probability because the number of cells. 4,600 cells include many cells of low quality therefore makes the cluster result undesirable. One thing you can try quickly is to change consecutive promoter coverage to filter cells to 1,500 cells and cluster again
I will update the barcode filtering parameter shortly.

**Comment by jeewonyang** [comment]
Thank you for your reply! I really like the way this pipeline is formatted, and I was hoping this would ease my analysis as well... 

1. Would you be able to help me understand what exactly a consecutive promoter coverage means..? Is it simply promoter regions merged&sorted together? I downloaded the mm10.consecutive_promoter.bed file from the server directly, but I wasn't quite sure what region it is actually specifying.
2. I increased the threshold to 0.09, which resulted in giving 1,465 cells. However I suddenly ran into an error that I've never seen before : 
`Error in La.svd(V) : error code 1 from Lapack routine 'dgesdd'` 
Is this anything expected along the pipeline?

+3. I've also inspected the actual *.jacard files to check whether it contains the right value (which should be 0 < index < 1, from my understanding). Yet, what I find is a matrix with a value of 1000.00, and 0s on the diagonal. Is this an error or is it just the way jaccard matrix displays in my text editor...? I wasn't able to look at the snATAC_jacard code itself as it seems to be in a non-readable format.

Thank you so much in advance for all your help.

**Comment by jeewonyang** [comment]
(update on 3) Hello, I actually just found out that my bmat file didn't contain any 1s in it from the first place. I'm trying to understand why the bmat function haven't been calling in the peaks... Do you think this can be a python version specific issue? (I'm currently using python 2.7)

+ In python version 2.x, `while True` might need to be `while 1`.
After specifying this part the code at least runs through, but I'm still not getting any intersections. Would you be able to specify which version of pybedtools and Python you're using?

**Comment by r3fang** [comment]
1. consecutive_promoters are promoters that are accessible across all tissues/cell lines using all published bulk ATAC/DHS sites. 
2. python 2.7 should be fine. i never saw this error ... 
3. because jaccard index is very small, it is jaccard x 1000

**Comment by jeewonyang** [comment]
Thanks for clarifying for me!

I think something might not've run through when I chunked the read file up. I managed to get this working now :) thank you so much!
